###
# CGET 200
GET http://127.0.0.1:80/api/v1/logs
Accept: application/json

###
# GET ERROR 422 (validación parámetros)
GET http://127.0.0.1:80/api/v1/logs/9999
Accept: application/json

###
# GET 200
GET http://127.0.0.1:80/api/v1/logs/1234
Accept: application/json

###
# DELETE 204
DELETE http://127.0.0.1:80/api/v1/logs/1234
Accept: application/json

###
# POST 201
POST http://127.0.0.1:80/api/v1/logs
Content-Type: application/json

{
  "id": 1111,
  "fecha": "13/04/2022",
  "mensaje": "Mensaje log",
  "prioridad": "Alta",
  "usuario": "Ramón",
  "subsistema": 1
}

###
# COPTIONS 204
OPTIONS http://127.0.0.1:80/api/v1/logs
Content-Type: application/json

###
# OPTIONS 204
OPTIONS http://127.0.0.1:80/api/v1/logs/1111
Content-Type: application/json

###
# POST 201 (dinámico)
POST http://127.0.0.1:80/api/v1/logs
Prefer: dynamic=true
Content-Type: application/json

{
  "id": 1111,
  "fecha": "13/04/2022",
  "mensaje": "Mensaje log",
  "prioridad": "Alta",
  "usuario": "Ramón",
  "subsistema": 1
}

###
# PUT 422 (dinámico) - Falta cabecera If-Match
PUT http://127.0.0.1:80/api/v1/logs/1234
Prefer: dynamic=true
Content-Type: application/json

{
  "nombre": "ETSISI logs"
}

###
# PUT 200 (dinámico)
PUT http://127.0.0.1:80/api/v1/logs/1234
If-Match: 12345
Prefer: dynamic=true
Content-Type: application/json

{
  "nombre": "ETSISI logs"
}

###
# CGET 404
GET http://127.0.0.1:80/api/v1/logs
Prefer: code=404
Accept: application/problem+json

###
# DELETE 404
DELETE http://127.0.0.1:80/api/v1/logs/1234
Prefer: code=404

###
# POST 422
POST http://127.0.0.1:80/api/v1/logs
Prefer: code=422
Content-Type: application/json

{
  "id": 1111,
  "fecha": "13/04/2022",
  "mensaje": "Mensaje log",
  "usuario": "Ramón",
  "subsistema": 1
}

###
# PUT 404 (dinámico) - Not Found
PUT http://127.0.0.1:80/api/v1/logs/1234
If-Match: a1b2c3d4e5f6
Prefer: code=404
Content-Type: application/json

{
  "nombre": "ETSISI logs"
}

###
# PUT 422 (dinámico) - Falta cabecera If-Match
PUT http://127.0.0.1:80/api/v1/logs/1234
Prefer: code=422
Content-Type: application/json

{
  "nombre": "ETSISI logs"
}
